import { createAction } from 'redux-actions';


export const FAVORITES_CLEAR = createAction('FAVORITES/CLEAR');

export const FAVORITES_SUCCESS = createAction('FAVORITES/SUCCESS');
export const FAVORITES_FAILURE = createAction('FAVORITES/FAILURE');
export const FAVORITES_REQUEST = createAction('FAVORITES/REQUEST');

export const FAVORITES_RESTART_SUCCESS = createAction('FAVORITES/RESTART/SUCCESS');
export const FAVORITES_RESTART_FAILURE = createAction('FAVORITES/RESTART/FAILURE');
export const FAVORITES_RESTART_REQUEST = createAction('FAVORITES/RESTART/REQUEST');

export const FAVORITES_GET_SUCCESS = createAction('FAVORITES/GET/SUCCESS');
export const FAVORITES_GET_FAILURE = createAction('FAVORITES/GET/FAILURE');
export const FAVORITES_GET_REQUEST = createAction('FAVORITES/GET/REQUEST');

export const FAVORITES_UPDATE_SUCCESS = createAction('FAVORITES/UPDATE/SUCCESS');
export const FAVORITES_UPDATE_FAILURE = createAction('FAVORITES/UPDATE/FAILURE');
export const FAVORITES_UPDATE_REQUEST = createAction('FAVORITES/UPDATE/REQUEST');

export const FAVORITES_CREATE_SUCCESS = createAction('FAVORITES/CREATE/SUCCESS');
export const FAVORITES_CREATE_FAILURE = createAction('FAVORITES/CREATE/FAILURE');
export const FAVORITES_CREATE_REQUEST = createAction('FAVORITES/CREATE/REQUEST');


export const FAVORITES_REMOVE_SUCCESS = createAction('FAVORITES/REMOVE/SUCCESS');
export const FAVORITES_REMOVE_FAILURE = createAction('FAVORITES/REMOVE/FAILURE');
export const FAVORITES_REMOVE_REQUEST = createAction('FAVORITES/REMOVE/REQUEST');

export const FAVORITES_ALLOWED_SUCCESS = createAction('FAVORITES/ALLOWED/SUCCESS');
export const FAVORITES_ALLOWED_FAILURE = createAction('FAVORITES/ALLOWED/FAILURE');
export const FAVORITES_ALLOWED_REQUEST = createAction('FAVORITES/ALLOWED/REQUEST');
